# Generated by Django 4.1.7 on 2023-02-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0002_alter_category_is_active_alter_customer_passport_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='not_completed',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
