# Generated by Django 4.1.7 on 2023-02-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0003_purchase_not_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
