# Generated by Django 4.1.7 on 2023-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0005_purchaseitem_remove_purchase_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='cost',
            new_name='product_cost',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='description',
            new_name='purchase_description',
        ),
    ]
