# Generated by Django 4.1.7 on 2023-03-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0008_purchase_current_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='next_payment_date',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
