# Generated by Django 4.1.7 on 2023-04-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0011_purchase_last_payment_date_alter_payment_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='last_payment_date',
            new_name='final_payment_date',
        ),
    ]
